"""
HTML template for individual Compose component and example preview pages.
"""

HTML_TEMPLATE = """{autogenerated_header}
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="preview/generator/generate_component_pages.py">
    <title>{title} &mdash; Jetpack Compose &mdash; Android Developers</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;600;700&family=Google+Sans+Text:wght@400;500;600;700&family=Google+Sans+Code:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../style.css">
</head>
<body>
    <header class="devsite-header">
        <a href="../index.html" class="devsite-brand" title="Android Developers">
            <img src="https://www.gstatic.com/devrel-devsite/prod/v826fb839c0b38141980abf47020a61dc3ff340cbde624f57178f4c01d184ef87/android/images/lockup.png" alt="Android Developers" class="devsite-brand-logo">
            <span class="devsite-brand-badge">Compose Previews</span>
        </a>
        <div class="devsite-header-actions">
            <a href="theme-builder.html" class="header-btn" title="Open Material Theme Builder">
                &#127912; Theme Builder
            </a>
            <a href="https://github.com/android/snippets" target="_blank" class="header-btn" title="View android/snippets on GitHub">
                GitHub Repository
            </a>
            <button class="header-btn" onclick="toggleTheme()" id="themeBtn" title="Toggle Light / Dark Mode">
                &#9681; Theme
            </button>
        </div>
    </header>

    <div class="doc-layout">
        {left_sidebar_html}

        <article class="devsite-article component-article" data-component-id="{id}">
            <div class="page-header" id="overview">
                <span class="category-tag">{category_name}</span>
                <div class="title-with-tag" style="display: flex; align-items: center; flex-wrap: wrap; gap: 12px; margin-bottom: 12px;">
                    <h1 class="component-title" style="margin-bottom: 0;">{title}</h1>
                    <span class="import-tag" title="Click to copy import" onclick="navigator.clipboard.writeText('{import_symbol}').then(() => {{ const el = this; const old = el.innerHTML; el.innerHTML = '<code>Copied!</code>'; setTimeout(() => el.innerHTML = old, 1500); }})"><code>{import_symbol}</code></span>
                </div>
                <p class="component-lead">{lead_description}</p>
            </div>

            <div class="page-anchor-pills">
                <a href="#preview-screenshot" class="page-anchor-pill">Screenshot</a>
                <a href="#interactive-preview" class="page-anchor-pill">Interactive Preview</a>
                <a href="#code-snippets" class="page-anchor-pill">Code Snippet</a>
                <a href="#api-surface" class="page-anchor-pill">API Parameters</a>
            </div>

            {family_overview_html}

            <div class="component-workspace">
                <div class="component-main-content">
                    <section id="preview-screenshot">
                        <h2 class="section-heading">Preview Screenshot</h2>
                        <div class="screenshot-card">
                            <img src="../screenshots/{screenshot_id}.png" alt="{title} Preview Screenshot" class="preview-img" onerror="this.onerror=null; this.src='../screenshots/{fallback_screenshot_id}.png';">
                        </div>
                    </section>

                    <section id="code-snippets">
                        <h2 class="section-heading">
                            <span>Code Snippet from <code>{file_name}</code></span>
                        </h2>
                        <div class="code-container">
                            <div class="code-header">
                                <span>{file_name}</span>
                                <button class="copy-btn" onclick="copyCode()">Copy</button>
                            </div>
                            <pre class="code-block"><code id="codeSnippet" class="language-kotlin">{code_snippet_escaped}</code></pre>
                            <div class="code-footer">
                                <a href="https://github.com/android/snippets/blob/main/compose/snippets/src/main/java/com/example/compose/snippets/components/{file_name}" target="_blank" class="code-link">
                                    <span>View full source</span>
                                    <svg viewBox="0 0 24 24" width="14" height="14" fill="currentColor"><path d="M19 19H5V5h7V3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/></svg>
                                </a>
                            </div>
                        </div>
                    </section>

                    <section id="api-surface">
                        <h2 class="section-heading">Key API Parameters</h2>
                        <table class="api-table">
                            <thead>
                                <tr>
                                    <th>Parameter</th>
                                    <th>Type</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                {api_rows_html}
                            </tbody>
                        </table>
                    </section>
                </div>

                <div class="component-phone-preview" id="interactive-preview">
                    <div class="phone-preview-card">
                        <div class="phone-preview-toolbar">
                            <span class="wasm-badge">
                                <span class="wasm-dot"></span>
                                Live Preview
                            </span>
                            <div class="wasm-actions">
                                <button class="wasm-btn" onclick="reloadWasm()" title="Reload WASM Canvas">&#8635; Reload</button>
                                <a id="wasmFullscreenBtn" href="../wasm.html?snippet={id}&standalone=true&density=1.0" target="_blank" class="wasm-btn" title="Open Fullscreen in New Tab">&#x26F6; Fullscreen</a>
                            </div>
                        </div>

                        <div class="phone-theme-row">
                            <span class="theme-picker-label">Theme:</span>
                            <div class="theme-swatches">
                                <button type="button" class="theme-swatch" data-preset="android_green" data-color="#3DDC84" title="Android Green" style="background-color: #3DDC84;" onclick="changeWasmTheme('android_green', '#3DDC84', this)"></button>
                                <button type="button" class="theme-swatch" data-preset="baseline_purple" data-color="#6750A4" title="Material 3 Purple" style="background-color: #6750A4;" onclick="changeWasmTheme('baseline_purple', '#6750A4', this)"></button>
                                <button type="button" class="theme-swatch" data-preset="google_blue" data-color="#4285F4" title="Google Blue" style="background-color: #4285F4;" onclick="changeWasmTheme('google_blue', '#4285F4', this)"></button>
                                <button type="button" class="theme-swatch" data-preset="ocean_teal" data-color="#006A6A" title="Ocean Teal" style="background-color: #006A6A;" onclick="changeWasmTheme('ocean_teal', '#006A6A', this)"></button>
                                <button type="button" class="theme-swatch" data-preset="terracotta_rose" data-color="#9C4146" title="Terracotta Rose" style="background-color: #9C4146;" onclick="changeWasmTheme('terracotta_rose', '#9C4146', this)"></button>
                                <button type="button" class="theme-swatch" data-preset="amber_gold" data-color="#825500" title="Amber Gold" style="background-color: #825500;" onclick="changeWasmTheme('amber_gold', '#825500', this)"></button>
                                <button type="button" class="theme-swatch active" data-preset="monochrome" data-color="#5F6368" title="Monochrome" style="background-color: #5F6368;" onclick="changeWasmTheme('monochrome', '#5F6368', this)"></button>
                                <label class="theme-swatch theme-custom-label" title="Custom Seed Color">
                                    <input type="color" id="customColorInput" value="#5F6368" onchange="changeWasmCustomColor(this.value)">
                                    <span class="custom-color-icon">+</span>
                                </label>
                            </div>
                        </div>

                        <div class="pixel-phone-wrapper">
                            <div class="pixel-phone-device">
                                <div class="pixel-phone-speaker"></div>
                                <div class="pixel-phone-notch">
                                    <div class="pixel-phone-camera"></div>
                                </div>
                                <div class="pixel-phone-screen">
                                    <iframe id="wasmFrame" src="../wasm.html#/snippet/{id}" class="wasm-frame" title="{title} Interactive Preview"></iframe>
                                </div>
                            </div>
                            <div class="pixel-phone-caption">
                                Compiled with Compose Multiplatform. There may be slight visual differences with Android.
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="feedback-card">
                <div>
                    <div class="feedback-title">Found a problem with this component or preview?</div>
                    <div class="feedback-desc">Report an issue on GitHub with your current page context pre-filled.</div>
                </div>
                <a href="{report_issue_url}" target="_blank" rel="noopener noreferrer" class="header-btn report-btn" style="padding: 8px 16px; font-weight: 500;">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" style="vertical-align: -2px;"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/></svg>
                    <span>Report a problem</span>
                </a>
            </div>

            <div class="bottom-nav">
                {prev_link_html}
                <a href="../index.html" class="bottom-nav-link" style="text-align: center;">
                    <span class="bottom-nav-label">Back to</span>
                    <span class="bottom-nav-title">All Components Catalog</span>
                </a>
                {next_link_html}
            </div>
        </article>

        <aside class="devsite-page-nav" id="onThisPageNav" aria-label="On this page">
            <div class="page-nav-title">On this page</div>
            <ul class="page-nav-list">
                <li class="page-nav-item"><a href="#overview" class="page-nav-link active">Overview</a></li>
                {family_nav_item}
                <li class="page-nav-item"><a href="#preview-screenshot" class="page-nav-link">Preview screenshot</a></li>
                <li class="page-nav-item"><a href="#interactive-preview" class="page-nav-link">Interactive preview</a></li>
                <li class="page-nav-item"><a href="#code-snippets" class="page-nav-link">Code snippet</a></li>
                <li class="page-nav-item"><a href="#api-surface" class="page-nav-link">API parameters</a></li>
            </ul>
        </aside>
    </div>

    <script src="../js/prism.min.js"></script>
    <script src="../js/prism-kotlin.min.js"></script>
    <script>
        let activeSnippetId = '{id}';
        let currentWasmPreset = 'monochrome';
        let currentWasmColor = '#5F6368';

        function updateWasmTheme() {{
            const html = document.documentElement;
            const theme = html.getAttribute('data-theme') || 'light';
            const curArticle = document.querySelector('article.component-article');
            const snippetId = curArticle?.getAttribute('data-component-id') || activeSnippetId;
            const hash = `theme=${{theme}}&preset=${{currentWasmPreset}}&seed=${{encodeURIComponent(currentWasmColor)}}`;

            const fsBtn = document.getElementById('wasmFullscreenBtn');
            if (fsBtn) {{
                fsBtn.setAttribute('href', `../wasm.html?snippet=${{snippetId}}&standalone=true&density=1.0#${{hash}}`);
            }}

            const frame = document.getElementById('wasmFrame');
            if (frame && frame.contentWindow) {{
                try {{
                    frame.contentWindow.postMessage(JSON.stringify({{
                        type: 'SET_THEME',
                        snippet: snippetId,
                        theme: theme,
                        preset: currentWasmPreset,
                        color: currentWasmColor
                    }}), '*');
                }} catch (e) {{}}
            }}
        }}

        function toggleTheme() {{
            const html = document.documentElement;
            const current = html.getAttribute('data-theme') || 'light';
            const next = current === 'light' ? 'dark' : 'light';
            html.setAttribute('data-theme', next);
            localStorage.setItem('theme', next);
            updateWasmTheme();
        }}

        function changeWasmTheme(preset, color, btn) {{
            currentWasmPreset = preset;
            currentWasmColor = color;
            document.querySelectorAll('.theme-swatch').forEach(s => s.classList.remove('active'));
            if (btn) btn.classList.add('active');
            updateWasmTheme();
        }}

        function changeWasmCustomColor(color) {{
            currentWasmPreset = 'custom';
            currentWasmColor = color;
            document.querySelectorAll('.theme-swatch').forEach(s => s.classList.remove('active'));
            updateWasmTheme();
        }}

        function reloadWasm() {{
            const frame = document.getElementById('wasmFrame');
            if (frame) frame.src = frame.src;
        }}

        function copyCode() {{
            const code = document.getElementById('codeSnippet').innerText;
            navigator.clipboard.writeText(code).then(() => {{
                const btn = document.querySelector('.copy-btn');
                btn.textContent = 'Copied!';
                setTimeout(() => {{ btn.textContent = 'Copy'; }}, 2000);
            }});
        }}

        function handleParentNavClick(target, event) {{
            const parentItem = target.closest('.nav-item-parent');
            if (!parentItem) return;
            const subList = parentItem.querySelector('.nav-sub-list');
            const arrow = parentItem.querySelector('.nav-sub-arrow');
            if (subList) {{
                subList.style.display = 'block';
                if (arrow) arrow.innerHTML = '&#9662;';
            }}
        }}

        function toggleNavSub(target, event) {{
            if (event) {{
                event.preventDefault();
                event.stopPropagation();
            }}
            const parentItem = target.closest('.nav-item-parent');
            if (!parentItem) return;
            const subList = parentItem.querySelector('.nav-sub-list');
            const arrow = parentItem.querySelector('.nav-sub-arrow');
            if (!subList) return;
            if (subList.style.display === 'none') {{
                subList.style.display = 'block';
                if (arrow) arrow.innerHTML = '&#9662;';
            }} else {{
                subList.style.display = 'none';
                if (arrow) arrow.innerHTML = '&#9656;';
            }}
        }}

        function filterNav(query) {{
            query = query.toLowerCase().trim();
            const categories = document.querySelectorAll('.nav-tree-category');
            categories.forEach(cat => {{
                const items = cat.querySelectorAll('.nav-item');
                let catHasMatch = false;

                items.forEach(item => {{
                    const title = item.getAttribute('data-title') || '';
                    const subList = item.querySelector('.nav-sub-list');
                    const subArrow = item.querySelector('.nav-sub-arrow');
                    const subItems = item.querySelectorAll('.nav-sub-item');
                    let itemMatch = title.includes(query);
                    let subMatch = false;

                    subItems.forEach(sub => {{
                        const subTitle = sub.getAttribute('data-title') || '';
                        const match = subTitle.includes(query);
                        if (match) {{
                            subMatch = true;
                            sub.style.display = 'block';
                        }} else if (query) {{
                            sub.style.display = 'none';
                        }} else {{
                            sub.style.display = 'block';
                        }}
                    }});

                    if (!query) {{
                        item.style.display = 'block';
                        if (subList) {{
                            subList.style.display = 'none';
                            if (subArrow) subArrow.innerHTML = '&#9656;';
                        }}
                    }} else if (itemMatch || subMatch) {{
                        item.style.display = 'block';
                        catHasMatch = true;
                        if (subList) {{
                            subList.style.display = 'block';
                            if (subArrow) subArrow.innerHTML = '&#9662;';
                        }}
                    }} else {{
                        item.style.display = 'none';
                    }}
                }});

                cat.style.display = (!query || catHasMatch) ? 'block' : 'none';
            }});
        }}

        // Initialize theme from storage
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme) {{
            document.documentElement.setAttribute('data-theme', savedTheme);
        }}

        // =========================================================================
        // Client-Side SPA Router: Fast component switching without WASM teardown
        // =========================================================================
        const pageCache = new Map();
        let scrollObserver = null;

        function setupScrollspy() {{
            if (scrollObserver) {{
                scrollObserver.disconnect();
            }}
            scrollObserver = new IntersectionObserver((entries) => {{
                entries.forEach(entry => {{
                    if (entry.isIntersecting) {{
                        const id = entry.target.getAttribute('id');
                        document.querySelectorAll('.page-nav-link').forEach(link => {{
                            link.classList.toggle('active', link.getAttribute('href') === '#' + id);
                        }});
                    }}
                }});
            }}, {{ rootMargin: '0px 0px -70% 0px' }});

            document.querySelectorAll('article section, .page-header').forEach(section => {{
                scrollObserver.observe(section);
            }});
        }}

        function updateSidebarActive(targetFilename) {{
            const fn = targetFilename.split('/').pop().split('#')[0].split('?')[0];
            document.querySelectorAll('.devsite-book-nav .nav-link, .devsite-book-nav .nav-sub-item a').forEach(a => {{
                const href = a.getAttribute('href');
                if (!href) return;
                const aFn = href.split('/').pop().split('#')[0].split('?')[0];
                const isActive = (aFn === fn);
                a.classList.toggle('active', isActive);

                if (isActive) {{
                    const parentItem = a.closest('.nav-item-parent');
                    if (parentItem) {{
                        const subList = parentItem.querySelector('.nav-sub-list');
                        const arrow = parentItem.querySelector('.nav-sub-arrow');
                        if (subList) subList.style.display = 'block';
                        if (arrow) arrow.innerHTML = '&#9662;';
                    }}
                }}
            }});
        }}

        async function navigateToComponent(targetUrl, pushState = true) {{
            const cleanUrl = targetUrl.split('#')[0].split('?')[0];
            const hash = targetUrl.includes('#') ? targetUrl.split('#')[1] : null;
            const targetFilename = cleanUrl.split('/').pop();

            let pageData = pageCache.get(targetFilename);
            if (!pageData) {{
                try {{
                    const resp = await fetch(cleanUrl);
                    if (!resp.ok) {{
                        window.location.href = targetUrl;
                        return;
                    }}
                    const htmlText = await resp.text();
                    const parser = new DOMParser();
                    const doc = parser.parseFromString(htmlText, 'text/html');

                    const article = doc.querySelector('article.component-article');
                    if (!article) {{
                        window.location.href = targetUrl;
                        return;
                    }}

                    const newSnippetId = article.getAttribute('data-component-id') || targetFilename.replace('.html', '');

                    pageData = {{
                        title: doc.title,
                        pageHeaderHtml: doc.querySelector('.page-header')?.outerHTML || '',
                        pillsHtml: doc.querySelector('.page-anchor-pills')?.outerHTML || '',
                        familyHtml: doc.querySelector('.component-family-section')?.outerHTML || '',
                        mainContentHtml: doc.querySelector('.component-main-content')?.outerHTML || '',
                        feedbackCardHtml: doc.querySelector('.feedback-card')?.outerHTML || '',
                        bottomNavHtml: doc.querySelector('.bottom-nav')?.outerHTML || '',
                        onThisPageHtml: doc.querySelector('#onThisPageNav .page-nav-list')?.innerHTML || '',
                        snippetId: newSnippetId
                    }};
                    pageCache.set(targetFilename, pageData);
                }} catch (err) {{
                    window.location.href = targetUrl;
                    return;
                }}
            }}

            // Update DOM title & content
            document.title = pageData.title;

            const curArticle = document.querySelector('article.component-article');
            if (curArticle) {{
                curArticle.setAttribute('data-component-id', pageData.snippetId);

                const curHeader = document.querySelector('.page-header');
                if (curHeader && pageData.pageHeaderHtml) {{
                    curHeader.outerHTML = pageData.pageHeaderHtml;
                }}

                const curPills = document.querySelector('.page-anchor-pills');
                if (curPills && pageData.pillsHtml) {{
                    curPills.outerHTML = pageData.pillsHtml;
                }}

                let curFamily = document.querySelector('.component-family-section');
                if (pageData.familyHtml) {{
                    if (curFamily) {{
                        curFamily.outerHTML = pageData.familyHtml;
                    }} else {{
                        const pills = document.querySelector('.page-anchor-pills');
                        if (pills) pills.insertAdjacentHTML('afterend', pageData.familyHtml);
                    }}
                }} else if (curFamily) {{
                    curFamily.remove();
                }}

                const curMain = document.querySelector('.component-main-content');
                if (curMain && pageData.mainContentHtml) {{
                    curMain.outerHTML = pageData.mainContentHtml;
                }}

                const curFeedback = document.querySelector('.feedback-card');
                if (curFeedback && pageData.feedbackCardHtml) {{
                    curFeedback.outerHTML = pageData.feedbackCardHtml;
                }}

                const curBottom = document.querySelector('.bottom-nav');
                if (curBottom && pageData.bottomNavHtml) {{
                    curBottom.outerHTML = pageData.bottomNavHtml;
                }}
            }}

            // Update TOC in right sidebar
            const curToc = document.querySelector('#onThisPageNav .page-nav-list');
            if (curToc && pageData.onThisPageHtml) {{
                curToc.innerHTML = pageData.onThisPageHtml;
            }}

            // Update sidebar active selection
            updateSidebarActive(targetFilename);

            // Update active snippet id
            activeSnippetId = pageData.snippetId;

            // Update Fullscreen button link
            const fsBtn = document.getElementById('wasmFullscreenBtn');
            if (fsBtn) {{
                const curTheme = document.documentElement.getAttribute('data-theme') || 'light';
                const hash = `theme=${{curTheme}}&preset=${{currentWasmPreset}}&seed=${{encodeURIComponent(currentWasmColor)}}`;
                fsBtn.href = `../wasm.html?snippet=${{pageData.snippetId}}&standalone=true&density=1.0#${{hash}}`;
            }}

            // Keep the warm WASM running! Post message to instantly switch snippet without reload
            const frame = document.getElementById('wasmFrame');
            if (frame && frame.contentWindow) {{
                const curTheme = document.documentElement.getAttribute('data-theme') || 'light';
                try {{
                    frame.contentWindow.postMessage(JSON.stringify({{
                        type: 'SELECT_SNIPPET',
                        snippet: pageData.snippetId,
                        theme: curTheme,
                        preset: currentWasmPreset,
                        color: currentWasmColor
                    }}), '*');
                }} catch (e) {{}}
            }}

            // Re-run Prism code highlighting on the new snippet
            if (window.Prism) {{
                Prism.highlightAll();
            }}

            setupScrollspy();

            if (pushState) {{
                history.pushState({{ url: targetUrl, snippetId: pageData.snippetId }}, '', targetUrl);
            }}

            if (hash) {{
                const el = document.getElementById(hash);
                if (el) {{
                    el.scrollIntoView({{ behavior: 'smooth' }});
                    return;
                }}
            }}
            window.scrollTo({{ top: 0, behavior: 'instant' }});
        }}

        // Intercept internal component navigation clicks
        document.addEventListener('click', (e) => {{
            if (e.ctrlKey || e.metaKey || e.shiftKey || e.altKey || e.button !== 0) return;
            const link = e.target.closest('a');
            if (!link) return;
            const href = link.getAttribute('href');
            if (!href) return;
            if (href.startsWith('#') || href.startsWith('http://') || href.startsWith('https://') || href.startsWith('mailto:') || href.startsWith('javascript:')) return;
            if (link.getAttribute('target') === '_blank') return;
            if (href.includes('index.html') || href.includes('theme-builder.html')) return;

            const fn = href.split('#')[0].split('?')[0];
            if (fn.endsWith('.html')) {{
                e.preventDefault();
                navigateToComponent(href);
            }}
        }});

        window.addEventListener('popstate', (event) => {{
            if (event.state && event.state.snippetId) {{
                activeSnippetId = event.state.snippetId;
            }}
            const path = window.location.pathname.split('/').pop() || window.location.href;
            if (path.endsWith('.html')) {{
                navigateToComponent(path, false);
            }}
        }});

        // Initialize on DOM load
        window.addEventListener('DOMContentLoaded', () => {{
            const currentFilename = window.location.pathname.split('/').pop() || '{id}.html';
            const curArticle = document.querySelector('article.component-article');
            if (curArticle) {{
                activeSnippetId = curArticle.getAttribute('data-component-id') || '{id}';
                pageCache.set(currentFilename, {{
                    title: document.title,
                    pageHeaderHtml: document.querySelector('.page-header')?.outerHTML || '',
                    pillsHtml: document.querySelector('.page-anchor-pills')?.outerHTML || '',
                    familyHtml: document.querySelector('.component-family-section')?.outerHTML || '',
                    mainContentHtml: document.querySelector('.component-main-content')?.outerHTML || '',
                    feedbackCardHtml: document.querySelector('.feedback-card')?.outerHTML || '',
                    bottomNavHtml: document.querySelector('.bottom-nav')?.outerHTML || '',
                    onThisPageHtml: document.querySelector('#onThisPageNav .page-nav-list')?.innerHTML || '',
                    snippetId: activeSnippetId
                }});
            }}

            const frame = document.getElementById('wasmFrame');
            if (frame) {{
                frame.addEventListener('load', () => {{
                    setTimeout(updateWasmTheme, 150);
                }});
            }}
            updateWasmTheme();
            updateSidebarActive(currentFilename);
            setupScrollspy();
        }});
    </script>
</body>
</html>
"""

