import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "../.."))
SNIPPETS_SRC_DIR = os.path.join(
    ROOT_DIR, "compose/snippets/src/main/java/com/example/compose/snippets/components"
)
RESOURCES_DIR = os.path.join(ROOT_DIR, "preview/wasm/src/wasmJsMain/resources")

SNIPPET_CODE_MAP_FILE = os.path.join(
    ROOT_DIR,
    "preview/wasm/src/wasmJsMain/kotlin/com/example/compose/preview/wasm/registry/SnippetCodeMap.kt",
)


def make_kotlin_autogenerated_comment(script_relpath: str) -> str:
    """Returns a standardized banner comment warning that the Kotlin file is auto-generated."""
    from datetime import datetime, timezone

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""/*
 * =============================================================================
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
 * =============================================================================
 * This file was automatically generated by:
 *   {script_relpath}
 *
 * Generated on:
 *   {now_utc}
 *
 * WARNING:
 * Do NOT modify this file manually. Any changes will be overwritten when
 * the generator script is re-run.
 *
 * To make changes:
 * - Update the Compose code snippet in compose/snippets/src/main/java/com/example/compose/snippets/components/
 * - Update the extractor logic in preview/generator/snippet_extractor.py
 * - Run: python3 preview/generator/snippet_extractor.py
 * =============================================================================
 */"""
