#!/usr/bin/env python3
"""
Generate separate dedicated HTML pages for each Composable snippet matching developer.android.com branding.
Copies content, explanations, and structure from developer.android.com/develop/ui/compose/components.
Includes:
- Each example broken out into its own dedicated page (e.g. SingleChoiceSegmentedButton vs MultiChoiceSegmentedButton)
- Left side navigation tab (devsite-book-nav) with component category tree & search filter
- Code snippets extracted DIRECTLY from compose/snippets without duplication
- Embedded interactive WASM runner in Google Pixel 11 Pro phone layout
- Material 3 Dynamic Theme Builder preview
- Mapping to github.com/android/snippets repository
"""

import os
import sys
import html
import urllib.parse

# Ensure current directory is on sys.path for direct script execution
_DIR = os.path.dirname(os.path.abspath(__file__))
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)

from config import (
    SNIPPETS_SRC_DIR,
    COMPONENTS_DIR,
    DIST_COMPONENTS_DIR,
    make_autogenerated_comment,
)
from component_data import CATEGORIES, IMPORT_MAP
from snippet_extractor import extract_snippet, generate_snippet_code_map
from navigation import build_left_sidebar_html
from theme_builder_page import build_theme_builder_html
from component_template import HTML_TEMPLATE
from index_page import generate_index_page


def generate_all_pages():
    """Generates all dedicated component pages, the theme builder, and the catalog index."""
    generate_snippet_code_map()
    all_pages = []

    # Collect all pages to generate: individual examples + component family overviews
    for cat in CATEGORIES:
        for comp in cat["components"]:
            examples = comp.get("examples", [])
            file_name = comp["file"]

            # Add each individual example as a dedicated page
            for ex in examples:
                all_pages.append({
                    "id": ex["id"],
                    "title": ex["title"],
                    "category_id": cat["id"],
                    "category_name": cat["name"],
                    "file_name": file_name,
                    "lead_description": ex["description"],
                    "api_highlights": ex.get("api_highlights", comp.get("api_highlights", [])),
                    "tag": ex["tag"],
                    "parent_comp_id": comp["id"],
                    "parent_comp_title": comp["title"],
                    "screenshot_id": ex["id"],
                    "fallback_screenshot_id": comp["id"],
                    "is_family_overview": False
                })

            # Add the parent component page (overview/hub for this component family) if multiple examples or comp id != ex id
            if len(examples) > 1 or not any(ex["id"] == comp["id"] for ex in examples):
                all_pages.append({
                    "id": comp["id"],
                    "title": comp["title"],
                    "category_id": cat["id"],
                    "category_name": cat["name"],
                    "file_name": file_name,
                    "lead_description": comp["description"],
                    "api_highlights": comp.get("api_highlights", []),
                    "tag": examples[0]["tag"] if examples else "",
                    "examples": examples,
                    "screenshot_id": comp["id"],
                    "fallback_screenshot_id": comp["id"],
                    "is_family_overview": True
                })

    total = len(all_pages)
    print(f"Generating {total} dedicated component & example pages...")
    autogen_header = make_autogenerated_comment("preview/generator/generate_component_pages.py")

    for i, p in enumerate(all_pages):
        page_id = p["id"]
        title = p["title"]
        cat_id = p["category_id"]
        cat_name = p["category_name"]
        file_name = p["file_name"]
        lead_desc = p["lead_description"]
        real_filepath = os.path.join(SNIPPETS_SRC_DIR, file_name)

        # Code snippet extracted directly from compose/snippets (without START / END comment tags)
        if p["is_family_overview"]:
            snippets = []
            for ex in p.get("examples", []):
                code = extract_snippet(real_filepath, ex["tag"])
                if code:
                    snippets.append(code)
            code_snippet = "\n\n".join(snippets)
        else:
            code = extract_snippet(real_filepath, p["tag"])
            code_snippet = code if code else ""

        code_snippet_escaped = html.escape(code_snippet)

        api_rows = []
        for api in p["api_highlights"]:
            api_rows.append(f"""<tr>
                <td><code>{html.escape(api['param'])}</code></td>
                <td><code>{html.escape(api['type'])}</code></td>
                <td>{html.escape(api['desc'])}</td>
            </tr>""")
        api_rows_html = "\n".join(api_rows)

        # Family overview cards HTML (if component has multiple examples)
        family_overview_html = ""
        family_nav_item = ""
        if p["is_family_overview"] and len(p.get("examples", [])) > 1:
            family_cards = []
            for ex in p["examples"]:
                family_cards.append(f"""
                <a href="{ex['id']}.html" class="example-card">
                    <div class="example-card-title">{html.escape(ex['title'])}</div>
                    <div class="example-card-desc">{html.escape(ex['description'])}</div>
                    <div class="example-card-link">View &rarr;</div>
                </a>
                """)
            family_overview_html = f"""
            <section id="component-types" class="component-family-section">
                <h2 class="section-heading">Component Types in this Family</h2>
                <div class="examples-grid">
                    {''.join(family_cards)}
                </div>
            </section>
            """
            family_nav_item = '<li class="page-nav-item"><a href="#component-types" class="page-nav-link">Component types</a></li>'

        left_sidebar_html = build_left_sidebar_html(page_id)

        # Prev / Next navigation
        prev_link_html = ""
        if i > 0:
            prev_p = all_pages[i - 1]
            prev_link_html = f"""<a href="{prev_p['id']}.html" class="bottom-nav-link">
                <span class="bottom-nav-label">&larr; Previous</span>
                <span class="bottom-nav-title">{prev_p['title']}</span>
            </a>"""
        else:
            prev_link_html = "<div></div>"

        next_link_html = ""
        if i < total - 1:
            next_p = all_pages[i + 1]
            next_link_html = f"""<a href="{next_p['id']}.html" class="bottom-nav-link" style="text-align: right;">
                <span class="bottom-nav-label">Next &rarr;</span>
                <span class="bottom-nav-title">{next_p['title']}</span>
            </a>"""
        else:
            next_link_html = "<div></div>"

        import_symbol = IMPORT_MAP.get(
            page_id,
            IMPORT_MAP.get(p.get("parent_comp_id", ""), f"androidx.compose.material3.{title.replace(' ', '')}")
        )

        issue_title = urllib.parse.quote(f"[Preview Issue] Problem with {title} ({page_id})")
        issue_body = urllib.parse.quote(
f"""### Problem Report

**Component / Example:** {title} (`{page_id}`)
**Compose Import:** `{import_symbol}`
**Source File:** [`compose/snippets/src/main/java/com/example/compose/snippets/components/{file_name}`](https://github.com/android/snippets/blob/main/compose/snippets/src/main/java/com/example/compose/snippets/components/{file_name})

---

### Description of the Problem
<!-- Please describe what went wrong, what rendering or behavior issue occurred in the WASM preview or screenshot, or what code snippet needs updating -->


### Steps to Reproduce
1. Open component preview for `{title}`
2. 

### Expected Behavior
<!-- What did you expect to happen? -->


### Additional Context
<!-- Any browser or device details -->
"""
        )
        report_issue_url = f"https://github.com/android/snippets/issues/new?title={issue_title}&body={issue_body}"

        if page_id == "theme-builder":
            page_content = build_theme_builder_html(left_sidebar_html, report_issue_url, is_root=False)
        else:
            page_content = HTML_TEMPLATE.format(
                autogenerated_header=autogen_header,
                id=page_id,
                title=title,
                import_symbol=import_symbol,
                report_issue_url=report_issue_url,
                category_id=cat_id,
                category_name=cat_name,
                file_name=file_name,
                lead_description=lead_desc,
                left_sidebar_html=left_sidebar_html,
                family_overview_html=family_overview_html,
                family_nav_item=family_nav_item,
                screenshot_id=p["screenshot_id"],
                fallback_screenshot_id=p["fallback_screenshot_id"],
                code_snippet_escaped=code_snippet_escaped,
                api_rows_html=api_rows_html,
                prev_link_html=prev_link_html,
                next_link_html=next_link_html
            )

        out_path = os.path.join(COMPONENTS_DIR, f"{page_id}.html")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(page_content)

        dist_out_path = os.path.join(DIST_COMPONENTS_DIR, f"{page_id}.html")
        with open(dist_out_path, "w", encoding="utf-8") as f:
            f.write(page_content)

    print(f"All {total} pages generated successfully!")
    generate_index_page()


if __name__ == "__main__":
    generate_all_pages()
