"""
Generates the main index.html catalog overview page and copies static assets.
"""

import os
import sys
import shutil

_DIR = os.path.dirname(os.path.abspath(__file__))
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)

from config import RESOURCES_DIR, ROOT_DIR, make_autogenerated_comment
from component_data import CATEGORIES
from navigation import build_left_sidebar_html
from theme_builder_page import build_theme_builder_html

def generate_index_page():
    left_sidebar_html = build_left_sidebar_html(current_page_id=None, is_root=True)

    category_sections = []
    for cat in CATEGORIES:
        comp_cards = []
        for comp in cat["components"]:
            examples = comp.get("examples", [])
            # If the component family has multiple examples, add the family overview card first
            if len(examples) > 1:
                comp_cards.append(f"""
                <div class="catalog-card catalog-card-family">
                    <a href="components/{comp['id']}.html" style="text-decoration: none; color: inherit;">
                        <div class="catalog-card-img-container">
                            <img src="screenshots/{comp['id']}.png" alt="{comp['title']} Overview Preview" class="catalog-card-img" loading="lazy" onerror="this.onerror=null; this.src='screenshots/{examples[0]['id']}.png';">
                        </div>
                        <div class="catalog-card-body">
                            <span class="catalog-card-category">{cat['name']} &bull; Overview</span>
                            <h3 class="catalog-card-title">{comp['title']} (All variants)</h3>
                            <p class="catalog-card-desc">{comp['description']}</p>
                        </div>
                    </a>
                </div>
                """)

            # Add each individual example as its own dedicated card
            if examples:
                for ex in examples:
                    comp_cards.append(f"""
                    <div class="catalog-card">
                        <a href="components/{ex['id']}.html" style="text-decoration: none; color: inherit;">
                            <div class="catalog-card-img-container">
                                <img src="screenshots/{ex['id']}.png" alt="{ex['title']} Preview" class="catalog-card-img" loading="lazy" onerror="this.onerror=null; this.src='screenshots/{comp['id']}.png';">
                            </div>
                            <div class="catalog-card-body">
                                <span class="catalog-card-category">{cat['name']}</span>
                                <h3 class="catalog-card-title">{ex['title']}</h3>
                                <p class="catalog-card-desc">{ex['description']}</p>
                            </div>
                        </a>
                    </div>
                    """)
            else:
                comp_cards.append(f"""
                <div class="catalog-card">
                    <a href="components/{comp['id']}.html" style="text-decoration: none; color: inherit;">
                        <div class="catalog-card-img-container">
                            <img src="screenshots/{comp['id']}.png" alt="{comp['title']} Preview" class="catalog-card-img" loading="lazy">
                        </div>
                        <div class="catalog-card-body">
                            <span class="catalog-card-category">{cat['name']}</span>
                            <h3 class="catalog-card-title">{comp['title']}</h3>
                            <p class="catalog-card-desc">{comp['description']}</p>
                        </div>
                    </a>
                </div>
                """)

        category_sections.append(f"""
        <section id="cat-{cat['id']}" style="margin-bottom: 48px;">
            <h2 class="section-heading" style="border-bottom: 2px solid var(--android-green);">{cat['name']}</h2>
            <div class="catalog-grid">
                {''.join(comp_cards)}
            </div>
        </section>
        """)

    autogen_header = make_autogenerated_comment("preview/generator/index_page.py")
    index_html = f"""{autogen_header}
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="preview/generator/index_page.py">
    <title>Jetpack Compose Material Components &mdash; Android Developers</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;600;700&family=Google+Sans+Text:wght@400;500;600;700&family=Google+Sans+Code:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
    <link rel="prefetch" href="snippets-preview-wasm.wasm" as="fetch" crossorigin="anonymous">
    <link rel="prefetch" href="skiko.wasm" as="fetch" crossorigin="anonymous">
    <link rel="prefetch" href="wasm.html" as="document">
</head>
<body>
    <header class="devsite-header">
        <a href="index.html" class="devsite-brand" title="Android Developers">
            <img src="https://www.gstatic.com/devrel-devsite/prod/v826fb839c0b38141980abf47020a61dc3ff340cbde624f57178f4c01d184ef87/android/images/lockup.png" alt="Android Developers" class="devsite-brand-logo">
            <span class="devsite-brand-badge">Compose Previews</span>
        </a>
        <div class="devsite-header-actions">
            <a href="components/theme-builder.html" class="header-btn" title="Open Material Theme Builder">
                &#127912; Theme Builder
            </a>
            <a href="https://github.com/android/snippets" target="_blank" class="header-btn" title="View android/snippets on GitHub">
                GitHub Repository
            </a>
            <button class="header-btn" onclick="toggleTheme()">&#9681; Theme</button>
        </div>
    </header>
    <div class="doc-layout">
        {left_sidebar_html}
        <article class="devsite-article catalog-article">
            <h1 style="font-family: 'Google Sans', sans-serif; font-size: 2.2rem; font-weight: 700; margin-bottom: 8px;">
                Material 3 Components in Jetpack Compose
            </h1>
            <p style="font-size: 1.1rem; color: var(--text-secondary); margin-bottom: 32px;">
                Browse, preview, and test running WebAssembly snippets for official Material 3 Compose components.
            </p>
            {''.join(category_sections)}
            <div class="feedback-card">
                <div>
                    <div class="feedback-title">Found a problem with any component preview or snippet?</div>
                    <div class="feedback-desc">Report an issue on GitHub to help us improve the Android Snippets catalog.</div>
                </div>
                <a href="https://github.com/android/snippets/issues/new?title=%5BPreview%20Issue%5D%20Problem%20on%20Compose%20Previews%20Catalog&body=%23%23%23%20Problem%20Report%0A%0A**Page%3A**%20Compose%20Previews%20Catalog%20Overview%0A%0A---%0A%0A%23%23%23%20Description%20of%20the%20Problem%0A%3C!--%20Please%20describe%20what%20went%20wrong%20or%20what%20needs%20fixing%20--%3E%0A" target="_blank" rel="noopener noreferrer" class="header-btn report-btn" style="padding: 8px 16px; font-weight: 500;">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" style="vertical-align: -2px;"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/></svg>
                    <span>Report a problem</span>
                </a>
            </div>
        </article>
    </div>
    <script>
        function toggleTheme() {{
            const html = document.documentElement;
            const current = html.getAttribute('data-theme') || 'light';
            const next = current === 'light' ? 'dark' : 'light';
            html.setAttribute('data-theme', next);
            localStorage.setItem('theme', next);
        }}
        function handleParentNavClick(target, event) {{
            const parentItem = target.closest('.nav-item-parent');
            if (!parentItem) return;
            const subList = parentItem.querySelector('.nav-sub-list');
            const arrow = parentItem.querySelector('.nav-sub-arrow');
            if (subList && subList.style.display === 'none') {{
                subList.style.display = 'block';
                if (arrow) arrow.innerHTML = '&#9662;';
            }}
        }}
        function toggleNavSub(target, event) {{
            if (event) {{
                event.preventDefault();
                event.stopPropagation();
            }}
            const parentItem = target.closest('.nav-item-parent');
            if (!parentItem) return;
            const subList = parentItem.querySelector('.nav-sub-list');
            const arrow = parentItem.querySelector('.nav-sub-arrow');
            if (!subList) return;
            if (subList.style.display === 'none') {{
                subList.style.display = 'block';
                if (arrow) arrow.innerHTML = '&#9662;';
            }} else {{
                subList.style.display = 'none';
                if (arrow) arrow.innerHTML = '&#9656;';
            }}
        }}
        function filterNav(query) {{
            query = query.toLowerCase().trim();
            const categories = document.querySelectorAll('.nav-tree-category');
            categories.forEach(cat => {{
                const items = cat.querySelectorAll('.nav-item');
                let catHasMatch = false;

                items.forEach(item => {{
                    const title = item.getAttribute('data-title') || '';
                    const subList = item.querySelector('.nav-sub-list');
                    const subArrow = item.querySelector('.nav-sub-arrow');
                    const subItems = item.querySelectorAll('.nav-sub-item');
                    let itemMatch = title.includes(query);
                    let subMatch = false;

                    subItems.forEach(sub => {{
                        const subTitle = sub.getAttribute('data-title') || '';
                        const match = subTitle.includes(query);
                        if (match) {{
                            subMatch = true;
                            sub.style.display = 'block';
                        }} else if (query) {{
                            sub.style.display = 'none';
                        }} else {{
                            sub.style.display = 'block';
                        }}
                    }});

                    if (!query) {{
                        item.style.display = 'block';
                        if (subList) {{
                            subList.style.display = 'none';
                            if (subArrow) subArrow.innerHTML = '&#9656;';
                        }}
                    }} else if (itemMatch || subMatch) {{
                        item.style.display = 'block';
                        catHasMatch = true;
                        if (subList) {{
                            subList.style.display = 'block';
                            if (subArrow) subArrow.innerHTML = '&#9662;';
                        }}
                    }} else {{
                        item.style.display = 'none';
                    }}
                }});

                cat.style.display = (!query || catHasMatch) ? 'block' : 'none';
            }});
        }}
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme) document.documentElement.setAttribute('data-theme', savedTheme);
    </script>
</body>
</html>
"""

    with open(os.path.join(RESOURCES_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(index_html)
    with open(os.path.join(ROOT_DIR, "preview/wasm/build/dist/site/index.html"), "w", encoding="utf-8") as f:
        f.write(index_html)

    style_src = os.path.join(RESOURCES_DIR, "style.css")
    style_dist = os.path.join(ROOT_DIR, "preview/wasm/build/dist/site/style.css")
    if os.path.exists(style_src):
        import shutil
        shutil.copyfile(style_src, style_dist)

    js_src = os.path.join(RESOURCES_DIR, "js")
    js_dist = os.path.join(ROOT_DIR, "preview/wasm/build/dist/site/js")
    if os.path.exists(js_src):
        import shutil
        os.makedirs(js_dist, exist_ok=True)
        for f in os.listdir(js_src):
            shutil.copyfile(os.path.join(js_src, f), os.path.join(js_dist, f))

    # Also generate root theme-builder.html
    root_tb_issue = "https://github.com/android/snippets/issues/new?title=%5BTheme%20Builder%5D%20Issue%20with%20Material%20Theme%20Builder"
    root_tb_sidebar = build_left_sidebar_html(current_page_id="theme-builder", is_root=True)
    root_tb_html = build_theme_builder_html(root_tb_sidebar, root_tb_issue, is_root=True)
    with open(os.path.join(RESOURCES_DIR, "theme-builder.html"), "w", encoding="utf-8") as f:
        f.write(root_tb_html)
    with open(os.path.join(ROOT_DIR, "preview/wasm/build/dist/site/theme-builder.html"), "w", encoding="utf-8") as f:
        f.write(root_tb_html)


if __name__ == "__main__":
    generate_index_page()


