"""
Extracts code snippets from Compose snippet Kotlin sources and generates SnippetCodeMap.kt.
"""

import os
import sys
import re

_DIR = os.path.dirname(os.path.abspath(__file__))
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)

from config import SNIPPETS_SRC_DIR, SNIPPET_CODE_MAP_FILE, make_kotlin_autogenerated_comment
from component_data import CATEGORIES


def extract_snippet(filepath, tag):
    """Extracts a snippet bounded by [START tag] and [END tag] from filepath."""
    if not os.path.exists(filepath):
        return ""
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    in_tag = False
    in_exclude = False
    result = []
    start_pat = re.compile(rf"//\s*\[START\s+{re.escape(tag)}\]")
    end_pat = re.compile(rf"//\s*\[END\s+{re.escape(tag)}\]")

    for line in lines:
        if start_pat.search(line):
            in_tag = True
            continue
        if end_pat.search(line):
            in_tag = False
            continue
        if in_tag:
            if "// [START_EXCLUDE]" in line:
                in_exclude = True
                continue
            if "// [END_EXCLUDE]" in line:
                in_exclude = False
                continue
            if re.search(r"//\s*\[(START|END)[_\s]", line):
                continue
            if not in_exclude:
                result.append(line)

    return "".join(result).strip()


def escape_kotlin_multiline(s: str) -> str:
    """Escapes strings for Kotlin multiline string templates."""
    s = s.replace("$", '${"$" + ""}')
    s = s.replace('"""', '${"\\"\\"\\""}')
    return s


def generate_snippet_code_map():
    """Generates the SnippetCodeMap.kt registry file with all snippet sources."""
    entries = []
    seen_ids = set()

    for cat in CATEGORIES:
        for comp in cat["components"]:
            file_name = comp["file"]
            real_filepath = os.path.join(SNIPPETS_SRC_DIR, file_name)
            examples = comp.get("examples", [])
            for ex in examples:
                ex_id = ex["id"]
                if ex_id not in seen_ids:
                    code = extract_snippet(real_filepath, ex["tag"])
                    escaped = escape_kotlin_multiline(code)
                    entries.append(f'        "{ex_id}" to """{escaped}"""')
                    seen_ids.add(ex_id)
            comp_id = comp["id"]
            if comp_id not in seen_ids:
                if examples:
                    snippets = [extract_snippet(real_filepath, ex["tag"]) for ex in examples]
                    code = "\n\n".join([s for s in snippets if s])
                else:
                    code = ""
                escaped = escape_kotlin_multiline(code)
                entries.append(f'        "{comp_id}" to """{escaped}"""')
                seen_ids.add(comp_id)

    autogen_header = make_kotlin_autogenerated_comment("preview/generator/snippet_extractor.py")
    header = f"""{autogen_header}
/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.compose.preview.wasm.registry

object SnippetCodeMap {{
    private val codeMap: Map<String, String> = mapOf(
"""
    footer = """
    )

    fun getCode(id: String): String = codeMap[id] ?: "// No source code available for $id"
}
"""
    content = header + ",\n".join(entries) + footer
    with open(SNIPPET_CODE_MAP_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated SnippetCodeMap.kt with {len(entries)} snippet codes.")
