#!/usr/bin/env python3
"""
Extracts code snippets bounded by // [START <region_tag>] and // [END <region_tag>]
directly from Compose snippet Kotlin sources and generates SnippetCodeMap.kt.
"""

import glob
import os
import re
import sys

_DIR = os.path.dirname(os.path.abspath(__file__))
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)

from config import (
    SNIPPETS_SRC_DIR,
    SNIPPET_CODE_MAP_FILE,
    make_kotlin_autogenerated_comment,
)


def extract_all_snippets_from_file(filepath: str) -> dict[str, str]:
    """Extracts all snippets bounded by [START tag] and [END tag] from filepath."""
    if not os.path.exists(filepath):
        return {}
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    start_pat = re.compile(r"//\s*\[START\s+([A-Za-z0-9_]+)\]")
    end_pat = re.compile(r"//\s*\[END\s+([A-Za-z0-9_]+)\]")

    active_tags: dict[str, list[str]] = {}
    in_exclude = False
    extracted: dict[str, str] = {}

    for line in lines:
        m_start = start_pat.search(line)
        if m_start:
            tag = m_start.group(1)
            active_tags[tag] = []
            continue

        m_end = end_pat.search(line)
        if m_end:
            tag = m_end.group(1)
            if tag in active_tags:
                extracted[tag] = "".join(active_tags.pop(tag)).strip()
            continue

        if "// [START_EXCLUDE]" in line:
            in_exclude = True
            continue
        if "// [END_EXCLUDE]" in line:
            in_exclude = False
            continue
        if re.search(r"//\s*\[(START|END)[_\s]", line):
            continue

        if not in_exclude and active_tags:
            for buf in active_tags.values():
                buf.append(line)

    return extracted


def escape_kotlin_multiline(s: str) -> str:
    """Escapes strings for Kotlin multiline string templates."""
    s = s.replace("$", '${"$" + ""}')
    s = s.replace('"""', '${"\\"\\"\\""}')
    return s


def generate_snippet_code_map():
    """Generates the SnippetCodeMap.kt registry file keyed by region_tag."""
    entries = []
    seen_tags = set()

    for filepath in sorted(glob.glob(os.path.join(SNIPPETS_SRC_DIR, "*.kt"))):
        file_snippets = extract_all_snippets_from_file(filepath)
        for tag, code in file_snippets.items():
            if tag not in seen_tags and code:
                escaped = escape_kotlin_multiline(code)
                entries.append(f'        "{tag}" to """{escaped}"""')
                seen_tags.add(tag)

    autogen_header = make_kotlin_autogenerated_comment("preview/generator/snippet_extractor.py")
    header = f"""{autogen_header}
/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.compose.preview.wasm.registry

object SnippetCodeMap {{
    private val codeMap: Map<String, String> = mapOf(
"""
    footer = """
    )

    fun getCode(id: String): String = codeMap[id] ?: "// No source code available for $id"
}
"""
    content = header + ",\n".join(entries) + footer
    with open(SNIPPET_CODE_MAP_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated SnippetCodeMap.kt with {len(entries)} region_tag snippets.")


if __name__ == "__main__":
    generate_snippet_code_map()

