"""
Theme Builder HTML generation for Material 3 Dynamic Theme Builder tool.
"""

from config import make_autogenerated_comment


def build_theme_builder_html(left_sidebar_html, report_issue_url, is_root=False):
    css_path = "style.css" if is_root else "../style.css"
    brand_href = "index.html" if is_root else "../index.html"
    theme_builder_header_href = "theme-builder.html" if is_root else "theme-builder.html"
    wasm_src = "wasm.html?snippet=theme-builder" if is_root else "../wasm.html?snippet=theme-builder"
    fullscreen_href = "wasm.html?snippet=theme-builder&standalone=true&density=1.0" if is_root else "../wasm.html?snippet=theme-builder&standalone=true&density=1.0"
    screenshot_src = "screenshots/theme-builder.png" if is_root else "../screenshots/theme-builder.png"
    prism_js = "js/prism.min.js" if is_root else "../js/prism.min.js"
    prism_kt_js = "js/prism-kotlin.min.js" if is_root else "../js/prism-kotlin.min.js"
    index_href = "index.html" if is_root else "../index.html"
    prev_href = "components/swipe-item-example.html" if is_root else "swipe-item-example.html"

    autogenerated_header = make_autogenerated_comment("preview/generator/theme_builder_page.py")

    template = """{{AUTOGENERATED_HEADER}}
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="preview/generator/theme_builder_page.py">
    <title>Material Theme Builder &mdash; Jetpack Compose &mdash; Android Developers</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;600;700&family=Google+Sans+Text:wght@400;500;600;700&family=Google+Sans+Code:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{CSS_PATH}}">
</head>
<body>
    <header class="devsite-header">
        <a href="{{BRAND_HREF}}" class="devsite-brand" title="Android Developers">
            <img src="https://www.gstatic.com/devrel-devsite/prod/v826fb839c0b38141980abf47020a61dc3ff340cbde624f57178f4c01d184ef87/android/images/lockup.png" alt="Android Developers" class="devsite-brand-logo">
            <span class="devsite-brand-badge">Compose Previews</span>
        </a>
        <div class="devsite-header-actions">
            <a href="{{THEME_BUILDER_HEADER_HREF}}" class="header-btn" title="Open Material Theme Builder">
                &#127912; Theme Builder
            </a>
            <a href="https://github.com/android/snippets" target="_blank" class="header-btn" title="View android/snippets on GitHub">
                GitHub Repository
            </a>
            <button class="header-btn" onclick="toggleTheme()" id="themeBtn" title="Toggle Light / Dark Mode">
                &#9681; Theme
            </button>
        </div>
    </header>

    <div class="doc-layout">
        {{LEFT_SIDEBAR_HTML}}

        <article class="devsite-article tb-article">
            <div class="page-header" id="overview">
                <span class="category-tag">STYLES &amp; THEMING</span>
                <div class="title-with-tag" style="display: flex; align-items: center; flex-wrap: wrap; gap: 12px; margin-bottom: 12px;">
                    <h1 class="component-title" style="margin-bottom: 0;">Material Theme Builder</h1>
                    <span class="import-tag" title="Click to copy import" onclick="navigator.clipboard.writeText('androidx.compose.material3.MaterialTheme').then(() => { const el = this; const old = el.innerHTML; el.innerHTML = '<code>Copied!</code>'; setTimeout(() => el.innerHTML = old, 1500); })"><code>androidx.compose.material3.MaterialTheme</code></span>
                </div>
                <p class="component-lead">
                    Interactive Material 3 Theme Builder for Jetpack Compose. Select from official tonal presets or pick a custom brand seed color to dynamically generate accessible color roles, preview a real-world Compose application running live on WebAssembly, and export ready-to-use Compose theme code.
                </p>
            </div>

            <div class="tb-workspace">
                <section id="theme-controls">
                    <h2 class="section-heading">Theme Configuration</h2>
                    <div class="tb-controls-panel">
                        <div>
                            <div class="tb-section-title">
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M12 3c-4.97 0-9 4.03-9 9 0 2.12.74 4.07 1.97 5.61L4.35 19.4c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0l1.9-1.9C9.36 19.63 10.63 20 12 20c4.97 0 9-4.03 9-9s-4.03-9-9-9zm0 15c-3.31 0-6-2.69-6-6s2.69-6 6-6 6 2.69 6 6-2.69 6-6 6z"/></svg>
                                <span>Tonal Palette Presets</span>
                            </div>
                            <div class="tb-presets-row" id="presetsRow">
                                <button type="button" class="tb-preset-btn active" data-preset="monochrome" data-seed="#5F6368" onclick="selectPreset('monochrome', this)">
                                    <span class="tb-preset-dot" style="background: #5F6368;"></span>
                                    <span>Monochrome</span>
                                </button>
                                <button type="button" class="tb-preset-btn" data-preset="android_green" data-seed="#3DDC84" onclick="selectPreset('android_green', this)">
                                    <span class="tb-preset-dot" style="background: #3DDC84;"></span>
                                    <span>Android Green</span>
                                </button>
                                <button type="button" class="tb-preset-btn" data-preset="baseline_purple" data-seed="#6750A4" onclick="selectPreset('baseline_purple', this)">
                                    <span class="tb-preset-dot" style="background: #6750A4;"></span>
                                    <span>Material 3 Purple</span>
                                </button>
                                <button type="button" class="tb-preset-btn" data-preset="google_blue" data-seed="#4285F4" onclick="selectPreset('google_blue', this)">
                                    <span class="tb-preset-dot" style="background: #4285F4;"></span>
                                    <span>Google Blue</span>
                                </button>
                                <button type="button" class="tb-preset-btn" data-preset="ocean_teal" data-seed="#006A6A" onclick="selectPreset('ocean_teal', this)">
                                    <span class="tb-preset-dot" style="background: #006A6A;"></span>
                                    <span>Ocean Teal</span>
                                </button>
                                <button type="button" class="tb-preset-btn" data-preset="terracotta_rose" data-seed="#9C4146" onclick="selectPreset('terracotta_rose', this)">
                                    <span class="tb-preset-dot" style="background: #9C4146;"></span>
                                    <span>Terracotta Rose</span>
                                </button>
                                <button type="button" class="tb-preset-btn" data-preset="amber_gold" data-seed="#825500" onclick="selectPreset('amber_gold', this)">
                                    <span class="tb-preset-dot" style="background: #825500;"></span>
                                    <span>Amber Gold</span>
                                </button>
                            </div>
                        </div>

                        <div class="tb-input-row">
                            <div>
                                <div class="tb-section-title">
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M12 22C6.49 22 2 17.51 2 12S6.49 2 12 2s10 4.04 10 9c0 3.31-2.69 6-6 6h-1.77c-.28 0-.5.22-.5.5 0 .12.05.23.13.33.41.47.64 1.06.64 1.67 0 1.93-1.57 3.5-3.5 3.5zm-5.5-9c.83 0 1.5-.67 1.5-1.5S7.33 10 6.5 10 5 10.67 5 11.5 5.67 13 6.5 13zm3-4c.83 0 1.5-.67 1.5-1.5S10.33 6 9.5 6 8 6.67 8 7.5 8.67 9 9.5 9zm5 0c.83 0 1.5-.67 1.5-1.5S15.33 6 14.5 6 13 6.67 13 7.5 13.67 9 14.5 9zm3 4c.83 0 1.5-.67 1.5-1.5S18.33 10 17.5 10 16 10.67 16 11.5 16.67 13 17.5 13z"/></svg>
                                    <span>Custom Seed Color</span>
                                </div>
                                <div class="tb-color-input-wrapper">
                                    <input type="color" id="tbSeedPicker" class="tb-color-picker" value="#5F6368" oninput="onCustomSeedChange(this.value)">
                                    <input type="text" id="tbSeedHex" class="tb-hex-input" value="#5F6368" maxlength="7" placeholder="#5F6368" oninput="onHexInputChange(this.value)">
                                </div>
                            </div>

                            <div>
                                <div class="tb-section-title">
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M20 8.69V4h-4.69L12 .69 8.69 4H4v4.69L.69 12 4 15.31V20h4.69L12 23.31 15.31 20H20v-4.69L23.31 12 20 8.69zM12 18c-.89 0-1.74-.2-2.5-.55C11.56 16.5 13 14.42 13 12s-1.44-4.5-3.5-5.45C10.26 6.2 11.11 6 12 6c3.31 0 6 2.69 6 6s-2.69 6-6 6z"/></svg>
                                    <span>Color Mode</span>
                                </div>
                                <div class="tb-mode-toggle">
                                    <button type="button" id="btnModeLight" class="tb-mode-btn active" onclick="setAppMode('light')">&#9728; Light</button>
                                    <button type="button" id="btnModeDark" class="tb-mode-btn" onclick="setAppMode('dark')">&#9790; Dark</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <section id="interactive-preview">
                    <div class="tb-phone-wrapper">
                        <div class="tb-phone-toolbar">
                            <span class="wasm-badge">
                                <span class="wasm-dot"></span>
                                Live App Preview
                            </span>
                            <div class="wasm-actions">
                                <button class="wasm-btn" onclick="reloadWasm()" title="Reload Preview">&#8635; Reload</button>
                                <a id="wasmFullscreenBtn" href="{{FULLSCREEN_HREF}}" target="_blank" class="wasm-btn" title="Open Fullscreen in New Tab">&#x26F6; Fullscreen</a>
                            </div>
                        </div>
                        <div class="tb-phone-device">
                            <div class="tb-phone-notch">
                                <div class="tb-phone-speaker"></div>
                                <div class="tb-phone-camera"></div>
                            </div>
                            <div class="tb-phone-screen">
                                <iframe id="wasmFrame" src="{{WASM_SRC}}" title="Theme Builder Real-World Preview"></iframe>
                            </div>
                        </div>
                        <div class="tb-phone-caption">
                            Compiled with Compose Multiplatform. There may be slight visual differences with Android.
                        </div>
                    </div>
                </section>

                <section id="color-roles">
                    <h2 class="section-heading">Material 3 Color Roles</h2>
                    <p style="color: var(--text-secondary); margin-bottom: 16px;">
                        Tonal color roles dynamically mapped for your current theme and mode. Click any card to copy its hex value:
                    </p>
                    <div class="tb-roles-grid" id="rolesGrid"></div>
                </section>

                <section id="export-code">
                    <h2 class="section-heading">Export Jetpack Compose Code</h2>
                    <p style="color: var(--text-secondary); margin-bottom: 16px;">
                        Copy and paste these generated Kotlin files directly into your Android Studio Jetpack Compose project:
                    </p>
                    <div class="code-container">
                        <div class="tb-code-tabs">
                            <button type="button" class="tb-code-tab active" id="tabTheme" onclick="switchCodeTab('theme')">Theme.kt</button>
                            <button type="button" class="tb-code-tab" id="tabColor" onclick="switchCodeTab('color')">Color.kt</button>
                        </div>
                        <div class="code-header" style="border-top: none;">
                            <span id="codeFileLabel">Theme.kt</span>
                            <button class="copy-btn" onclick="copyCurrentCode()">Copy</button>
                        </div>
                        <pre class="code-block" style="max-height: 480px; overflow-y: auto;"><code id="tbCodeSnippet" class="language-kotlin"></code></pre>
                    </div>
                    <p class="wasm-disclaimer" style="margin-top: 14px; font-size: 0.85rem; color: var(--text-secondary); line-height: 1.5;">
                        Tip: Wrap your top-level composable hierarchy with <code>AppTheme { ... }</code> in <code>MainActivity.kt</code> to apply these colors across all Material 3 components.
                    </p>
                </section>

                <section id="preview-screenshot">
                    <h2 class="section-heading">Static Preview Screenshot</h2>
                    <p style="color: var(--text-secondary); margin-bottom: 16px;">
                        Pre-rendered Roborazzi screenshot recorded with the default theme:
                    </p>
                    <div class="screenshot-card">
                        <img src="{{SCREENSHOT_SRC}}" alt="Material Theme Builder Preview" class="preview-img">
                    </div>
                </section>
            </div>

            <div class="feedback-card">
                <div>
                    <div class="feedback-title">Found a problem with the Theme Builder or generated code?</div>
                    <div class="feedback-desc">Report an issue on GitHub to help us improve Material 3 theme generation.</div>
                </div>
                <a href="{{REPORT_ISSUE_URL}}" target="_blank" rel="noopener noreferrer" class="header-btn report-btn" style="padding: 8px 16px; font-weight: 500;">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" style="vertical-align: -2px;"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/></svg>
                    <span>Report a problem</span>
                </a>
            </div>

            <div class="bottom-nav">
                <a href="{{PREV_HREF}}" class="bottom-nav-link">
                    <span class="bottom-nav-label">&larr; Previous</span>
                    <span class="bottom-nav-title">Swipe to dismiss</span>
                </a>
                <a href="{{INDEX_HREF}}" class="bottom-nav-link" style="text-align: right;">
                    <span class="bottom-nav-label">Next &rarr;</span>
                    <span class="bottom-nav-title">All Components Catalog</span>
                </a>
            </div>
        </article>

        <aside class="devsite-page-nav" id="onThisPageNav" aria-label="On this page">
            <div class="page-nav-title">On this page</div>
            <ul class="page-nav-list">
                <li class="page-nav-item"><a href="#overview" class="page-nav-link active">Overview</a></li>
                <li class="page-nav-item"><a href="#theme-controls" class="page-nav-link">Theme configuration</a></li>
                <li class="page-nav-item"><a href="#interactive-preview" class="page-nav-link">Real-world preview</a></li>
                <li class="page-nav-item"><a href="#color-roles" class="page-nav-link">Color roles</a></li>
                <li class="page-nav-item"><a href="#export-code" class="page-nav-link">Export Compose code</a></li>
                <li class="page-nav-item"><a href="#preview-screenshot" class="page-nav-link">Preview screenshot</a></li>
            </ul>
        </aside>
    </div>

    <script src="{{PRISM_JS}}"></script>
    <script src="{{PRISM_KT_JS}}"></script>
    <script>
        const PRESETS = {
            monochrome: {
                name: 'Monochrome',
                seed: '#5F6368',
                light: {
                    primary: '#000000', onPrimary: '#FFFFFF', primaryContainer: '#E0E0E0', onPrimaryContainer: '#1F1F1F',
                    secondary: '#5F6368', onSecondary: '#FFFFFF', secondaryContainer: '#E8EAED', onSecondaryContainer: '#1F1F1F',
                    tertiary: '#3C4043', onTertiary: '#FFFFFF', tertiaryContainer: '#DADCE0', onTertiaryContainer: '#1F1F1F',
                    background: '#FFFFFF', onBackground: '#1F1F1F',
                    surface: '#FFFFFF', onSurface: '#1F1F1F',
                    surfaceVariant: '#E0E2E0', onSurfaceVariant: '#444746',
                    outline: '#747775', outlineVariant: '#C4C7C5'
                },
                dark: {
                    primary: '#E3E3E3', onPrimary: '#1F1F1F', primaryContainer: '#444746', onPrimaryContainer: '#E3E3E3',
                    secondary: '#C4C7C5', onSecondary: '#2D312E', secondaryContainer: '#444746', onSecondaryContainer: '#E2E3E0',
                    tertiary: '#E3E3E3', onTertiary: '#2D312E', tertiaryContainer: '#444746', onTertiaryContainer: '#E2E3E0',
                    background: '#121212', onBackground: '#E3E3E3',
                    surface: '#121212', onSurface: '#E3E3E3',
                    surfaceVariant: '#444746', onSurfaceVariant: '#C4C7C5',
                    outline: '#8E918F', outlineVariant: '#444746'
                }
            },
            android_green: {
                name: 'Android Green',
                seed: '#3DDC84',
                light: {
                    primary: '#006D3B', onPrimary: '#FFFFFF', primaryContainer: '#94F7B3', onPrimaryContainer: '#00210E',
                    secondary: '#4F6353', onSecondary: '#FFFFFF', secondaryContainer: '#D2E8D4', onSecondaryContainer: '#0D1F13',
                    tertiary: '#3A646E', onTertiary: '#FFFFFF', tertiaryContainer: '#BEEAF5', onTertiaryContainer: '#001F25',
                    background: '#F7FBF4', onBackground: '#191C19',
                    surface: '#F7FBF4', onSurface: '#191C19',
                    surfaceVariant: '#DCE5DB', onSurfaceVariant: '#414942',
                    outline: '#717971', outlineVariant: '#C0C9BF'
                },
                dark: {
                    primary: '#78DA99', onPrimary: '#00391C', primaryContainer: '#00522B', onPrimaryContainer: '#94F7B3',
                    secondary: '#B6CCB8', onSecondary: '#223527', secondaryContainer: '#384B3D', onSecondaryContainer: '#D2E8D4',
                    tertiary: '#A2CED9', onTertiary: '#02363F', tertiaryContainer: '#204D56', onTertiaryContainer: '#BEEAF5',
                    background: '#101411', onBackground: '#E1E3DE',
                    surface: '#101411', onSurface: '#E1E3DE',
                    surfaceVariant: '#414942', onSurfaceVariant: '#C0C9BF',
                    outline: '#8B938A', outlineVariant: '#414942'
                }
            },
            baseline_purple: {
                name: 'Material 3 Purple',
                seed: '#6750A4',
                light: {
                    primary: '#6750A4', onPrimary: '#FFFFFF', primaryContainer: '#EADDFF', onPrimaryContainer: '#21005D',
                    secondary: '#625B71', onSecondary: '#FFFFFF', secondaryContainer: '#E8DEF8', onSecondaryContainer: '#1D192B',
                    tertiary: '#7D5260', onTertiary: '#FFFFFF', tertiaryContainer: '#FFD8E4', onTertiaryContainer: '#31111D',
                    background: '#FEF7FF', onBackground: '#1D1B20',
                    surface: '#FEF7FF', onSurface: '#1D1B20',
                    surfaceVariant: '#E7E0EC', onSurfaceVariant: '#49454F',
                    outline: '#79747E', outlineVariant: '#CAC4D0'
                },
                dark: {
                    primary: '#D0BCFF', onPrimary: '#381E72', primaryContainer: '#4F378B', onPrimaryContainer: '#EADDFF',
                    secondary: '#CCC2DC', onSecondary: '#332D41', secondaryContainer: '#4A4458', onSecondaryContainer: '#E8DEF8',
                    tertiary: '#EFB8C8', onTertiary: '#492532', tertiaryContainer: '#633B48', onTertiaryContainer: '#FFD8E4',
                    background: '#141218', onBackground: '#E6E0E9',
                    surface: '#141218', onSurface: '#E6E0E9',
                    surfaceVariant: '#49454F', onSurfaceVariant: '#CAC4D0',
                    outline: '#938F99', outlineVariant: '#49454F'
                }
            },
            google_blue: {
                name: 'Google Blue',
                seed: '#4285F4',
                light: {
                    primary: '#005AC1', onPrimary: '#FFFFFF', primaryContainer: '#D8E2FF', onPrimaryContainer: '#001A41',
                    secondary: '#575E71', onSecondary: '#FFFFFF', secondaryContainer: '#DBE2F9', onSecondaryContainer: '#141B2C',
                    tertiary: '#715573', onTertiary: '#FFFFFF', tertiaryContainer: '#FBD7FC', onTertiaryContainer: '#29132D',
                    background: '#FDFBFF', onBackground: '#1A1B1F',
                    surface: '#FDFBFF', onSurface: '#1A1B1F',
                    surfaceVariant: '#E1E2EC', onSurfaceVariant: '#44474F',
                    outline: '#74777F', outlineVariant: '#C4C6D0'
                },
                dark: {
                    primary: '#ADC6FF', onPrimary: '#002E69', primaryContainer: '#004494', onPrimaryContainer: '#D8E2FF',
                    secondary: '#BFC6DC', onSecondary: '#293041', secondaryContainer: '#3F4759', onSecondaryContainer: '#DBE2F9',
                    tertiary: '#DEBCDF', onTertiary: '#402843', tertiaryContainer: '#583E5B', onTertiaryContainer: '#FBD7FC',
                    background: '#1A1B1F', onBackground: '#E3E2E6',
                    surface: '#1A1B1F', onSurface: '#E3E2E6',
                    surfaceVariant: '#44474F', onSurfaceVariant: '#C4C6D0',
                    outline: '#8E9099', outlineVariant: '#44474F'
                }
            },
            ocean_teal: {
                name: 'Ocean Teal',
                seed: '#006A6A',
                light: {
                    primary: '#006A6A', onPrimary: '#FFFFFF', primaryContainer: '#6FF7F7', onPrimaryContainer: '#002020',
                    secondary: '#4A6363', onSecondary: '#FFFFFF', secondaryContainer: '#CCE8E8', onSecondaryContainer: '#051F1F',
                    tertiary: '#4B607C', onTertiary: '#FFFFFF', tertiaryContainer: '#D3E4FF', onTertiaryContainer: '#041C35',
                    background: '#FAFDFB', onBackground: '#191C1C',
                    surface: '#FAFDFB', onSurface: '#191C1C',
                    surfaceVariant: '#DAE4E4', onSurfaceVariant: '#3F4948',
                    outline: '#6F7979', outlineVariant: '#BEC8C8'
                },
                dark: {
                    primary: '#4CDADA', onPrimary: '#003737', primaryContainer: '#004F4F', onPrimaryContainer: '#6FF7F7',
                    secondary: '#B0CCCC', onSecondary: '#1B3435', secondaryContainer: '#324B4B', onSecondaryContainer: '#CCE8E8',
                    tertiary: '#B3C8E8', onTertiary: '#1C314B', tertiaryContainer: '#334863', onTertiaryContainer: '#D3E4FF',
                    background: '#191C1C', onBackground: '#E0E3E3',
                    surface: '#191C1C', onSurface: '#E0E3E3',
                    surfaceVariant: '#3F4948', onSurfaceVariant: '#BEC8C8',
                    outline: '#899392', outlineVariant: '#3F4948'
                }
            },
            terracotta_rose: {
                name: 'Terracotta Rose',
                seed: '#9C4146',
                light: {
                    primary: '#904A4E', onPrimary: '#FFFFFF', primaryContainer: '#FFDAD9', onPrimaryContainer: '#3B080F',
                    secondary: '#775656', onSecondary: '#FFFFFF', secondaryContainer: '#FFDAD9', onSecondaryContainer: '#2C1516',
                    tertiary: '#755A2F', onTertiary: '#FFFFFF', tertiaryContainer: '#FFDDAE', onTertiaryContainer: '#281800',
                    background: '#FFF8F7', onBackground: '#201A1A',
                    surface: '#FFF8F7', onSurface: '#201A1A',
                    surfaceVariant: '#F5DDDC', onSurfaceVariant: '#534343',
                    outline: '#857372', outlineVariant: '#D8C2C1'
                },
                dark: {
                    primary: '#FFB3B6', onPrimary: '#561D22', primaryContainer: '#733337', onPrimaryContainer: '#FFDAD9',
                    secondary: '#E7BDBE', onSecondary: '#44292A', secondaryContainer: '#5D3F3F', onSecondaryContainer: '#FFDAD9',
                    tertiary: '#E5C18D', onTertiary: '#422C05', tertiaryContainer: '#5B421A', onTertiaryContainer: '#FFDDAE',
                    background: '#1A1112', onBackground: '#EDE0DF',
                    surface: '#1A1112', onSurface: '#EDE0DF',
                    surfaceVariant: '#534343', onSurfaceVariant: '#D8C2C1',
                    outline: '#A08C8C', outlineVariant: '#534343'
                }
            },
            amber_gold: {
                name: 'Amber Gold',
                seed: '#825500',
                light: {
                    primary: '#825500', onPrimary: '#FFFFFF', primaryContainer: '#FFDDAE', onPrimaryContainer: '#2A1800',
                    secondary: '#6F5B40', onSecondary: '#FFFFFF', secondaryContainer: '#FADEBC', onSecondaryContainer: '#271904',
                    tertiary: '#516440', onTertiary: '#FFFFFF', tertiaryContainer: '#D4EABB', onTertiaryContainer: '#102004',
                    background: '#FFFFFB', onBackground: '#1F1B16',
                    surface: '#FFFFFB', onSurface: '#1F1B16',
                    surfaceVariant: '#F0E0CF', onSurfaceVariant: '#4F4539',
                    outline: '#817567', outlineVariant: '#D3C4B4'
                },
                dark: {
                    primary: '#FFB951', onPrimary: '#452B00', primaryContainer: '#633F00', onPrimaryContainer: '#FFDDAE',
                    secondary: '#DDC2A1', onSecondary: '#3D2E15', secondaryContainer: '#56442A', onSecondaryContainer: '#FADEBC',
                    tertiary: '#B8CEA1', onTertiary: '#243516', tertiaryContainer: '#3A4C2A', onTertiaryContainer: '#D4EABB',
                    background: '#1F1B16', onBackground: '#EAE1D9',
                    surface: '#1F1B16', onSurface: '#EAE1D9',
                    surfaceVariant: '#4F4539', onSurfaceVariant: '#D3C4B4',
                    outline: '#9C8F80', outlineVariant: '#4F4539'
                }
            }
        };

        const ROLE_DEFINITIONS = [
            { key: 'primary', label: 'Primary' },
            { key: 'onPrimary', label: 'On Primary' },
            { key: 'primaryContainer', label: 'Primary Container' },
            { key: 'onPrimaryContainer', label: 'On Primary Container' },
            { key: 'secondary', label: 'Secondary' },
            { key: 'onSecondary', label: 'On Secondary' },
            { key: 'secondaryContainer', label: 'Secondary Container' },
            { key: 'onSecondaryContainer', label: 'On Secondary Container' },
            { key: 'tertiary', label: 'Tertiary' },
            { key: 'onTertiary', label: 'On Tertiary' },
            { key: 'tertiaryContainer', label: 'Tertiary Container' },
            { key: 'onTertiaryContainer', label: 'On Tertiary Container' },
            { key: 'surface', label: 'Surface' },
            { key: 'onSurface', label: 'On Surface' },
            { key: 'surfaceVariant', label: 'Surface Variant' },
            { key: 'onSurfaceVariant', label: 'On Surface Variant' },
            { key: 'background', label: 'Background' },
            { key: 'onBackground', label: 'On Background' },
            { key: 'outline', label: 'Outline' },
            { key: 'outlineVariant', label: 'Outline Variant' }
        ];

        let currentPreset = 'monochrome';
        let currentSeed = '#5F6368';
        let currentMode = 'light';
        let activeTab = 'theme';

        function toHex(rF, gF, bF) {
            const cl = (v) => Math.min(255, Math.max(0, Math.round(v * 255))).toString(16).padStart(2, '0').toUpperCase();
            return '#' + cl(rF) + cl(gF) + cl(bF);
        }

        function generateCustomColors(seedHex, isDark) {
            const hex = seedHex.replace('#', '');
            const r = parseInt(hex.substring(0, 2), 16) / 255;
            const g = parseInt(hex.substring(2, 4), 16) / 255;
            const b = parseInt(hex.substring(4, 6), 16) / 255;

            if (isDark) {
                const primary = toHex(Math.min(1, r * 1.3 + 0.2), Math.min(1, g * 1.3 + 0.2), Math.min(1, b * 1.3 + 0.2));
                const container = toHex(r * 0.45, g * 0.45, b * 0.45);
                const secondary = toHex(Math.min(1, b * 1.1 + 0.2), Math.min(1, r * 1.1 + 0.2), Math.min(1, g * 1.1 + 0.2));
                return {
                    primary: primary, onPrimary: '#001F0F', primaryContainer: container, onPrimaryContainer: '#E0FFE0',
                    secondary: secondary, onSecondary: '#1A1A1A', secondaryContainer: '#384B3D', onSecondaryContainer: '#D2E8D4',
                    tertiary: '#A2CED9', onTertiary: '#02363F', tertiaryContainer: '#204D56', onTertiaryContainer: '#BEEAF5',
                    background: '#121413', onBackground: '#E1E3DF',
                    surface: '#121413', onSurface: '#E1E3DF',
                    surfaceVariant: '#3B443E', onSurfaceVariant: '#BEC8C1',
                    outline: '#88938C', outlineVariant: '#3B443E'
                };
            } else {
                const primary = toHex(r * 0.75, g * 0.75, b * 0.75);
                const container = toHex(Math.min(1, r * 0.25 + 0.75), Math.min(1, g * 0.25 + 0.75), Math.min(1, b * 0.25 + 0.75));
                const secondary = toHex(b * 0.6, r * 0.6, g * 0.6);
                return {
                    primary: primary, onPrimary: '#FFFFFF', primaryContainer: container, onPrimaryContainer: '#00210E',
                    secondary: secondary, onSecondary: '#FFFFFF', secondaryContainer: '#D2E8D4', onSecondaryContainer: '#0D1F13',
                    tertiary: '#3A646E', onTertiary: '#FFFFFF', tertiaryContainer: '#BEEAF5', onTertiaryContainer: '#001F25',
                    background: '#FCFDFB', onBackground: '#191C1A',
                    surface: '#FCFDFB', onSurface: '#191C1A',
                    surfaceVariant: '#DCE5DC', onSurfaceVariant: '#414942',
                    outline: '#717972', outlineVariant: '#C0C9BF'
                };
            }
        }

        function getCurrentSchemes() {
            if (currentPreset !== 'custom' && PRESETS[currentPreset]) {
                return {
                    light: PRESETS[currentPreset].light,
                    dark: PRESETS[currentPreset].dark
                };
            } else {
                return {
                    light: generateCustomColors(currentSeed, false),
                    dark: generateCustomColors(currentSeed, true)
                };
            }
        }

        function getContrastColor(hex) {
            const clean = hex.replace('#', '');
            const r = parseInt(clean.substring(0, 2), 16);
            const g = parseInt(clean.substring(2, 4), 16);
            const b = parseInt(clean.substring(4, 6), 16);
            const yiq = ((r * 299) + (g * 587) + (b * 114)) / 1000;
            return (yiq >= 128) ? '#000000' : '#FFFFFF';
        }

        function renderRoleSwatches() {
            const schemes = getCurrentSchemes();
            const colors = currentMode === 'dark' ? schemes.dark : schemes.light;
            const grid = document.getElementById('rolesGrid');
            if (!grid) return;

            grid.innerHTML = '';
            ROLE_DEFINITIONS.forEach(role => {
                const hex = colors[role.key] || '#000000';
                const textCol = getContrastColor(hex);
                const borderStyle = (hex.toUpperCase() === '#FFFFFF' || hex.toUpperCase() === '#121212') ? 'border: 1px solid var(--border-color);' : '';

                const card = document.createElement('div');
                card.className = 'tb-role-card';
                card.style.cssText = `background-color: ${hex}; color: ${textCol}; ${borderStyle}`;
                card.title = `Click to copy ${hex}`;
                card.onclick = () => copyRoleHex(hex, role.label, card);

                card.innerHTML = `
                    <div class="tb-role-name">${role.label}</div>
                    <div class="tb-role-hex">${hex}</div>
                `;
                grid.appendChild(card);
            });
        }

        function copyRoleHex(hex, label, cardEl) {
            navigator.clipboard.writeText(hex).then(() => {
                const hexEl = cardEl.querySelector('.tb-role-hex');
                if (hexEl) {
                    const old = hexEl.textContent;
                    hexEl.textContent = 'Copied!';
                    setTimeout(() => { hexEl.textContent = old; }, 1200);
                }
            });
        }

        function toArgb(hex) {
            return '0xFF' + hex.replace('#', '').toUpperCase();
        }

        function generateColorKt(light, dark) {
            return `package com.example.compose.theme

import androidx.compose.ui.graphics.Color

// Light Color Roles
val PrimaryLight = Color(${toArgb(light.primary)})
val OnPrimaryLight = Color(${toArgb(light.onPrimary)})
val PrimaryContainerLight = Color(${toArgb(light.primaryContainer)})
val OnPrimaryContainerLight = Color(${toArgb(light.onPrimaryContainer)})
val SecondaryLight = Color(${toArgb(light.secondary)})
val OnSecondaryLight = Color(${toArgb(light.onSecondary)})
val SecondaryContainerLight = Color(${toArgb(light.secondaryContainer)})
val OnSecondaryContainerLight = Color(${toArgb(light.onSecondaryContainer)})
val TertiaryLight = Color(${toArgb(light.tertiary)})
val OnTertiaryLight = Color(${toArgb(light.onTertiary)})
val TertiaryContainerLight = Color(${toArgb(light.tertiaryContainer)})
val OnTertiaryContainerLight = Color(${toArgb(light.onTertiaryContainer)})
val BackgroundLight = Color(${toArgb(light.background)})
val OnBackgroundLight = Color(${toArgb(light.onBackground)})
val SurfaceLight = Color(${toArgb(light.surface)})
val OnSurfaceLight = Color(${toArgb(light.onSurface)})
val SurfaceVariantLight = Color(${toArgb(light.surfaceVariant)})
val OnSurfaceVariantLight = Color(${toArgb(light.onSurfaceVariant)})
val OutlineLight = Color(${toArgb(light.outline)})
val OutlineVariantLight = Color(${toArgb(light.outlineVariant)})

// Dark Color Roles
val PrimaryDark = Color(${toArgb(dark.primary)})
val OnPrimaryDark = Color(${toArgb(dark.onPrimary)})
val PrimaryContainerDark = Color(${toArgb(dark.primaryContainer)})
val OnPrimaryContainerDark = Color(${toArgb(dark.onPrimaryContainer)})
val SecondaryDark = Color(${toArgb(dark.secondary)})
val OnSecondaryDark = Color(${toArgb(dark.onSecondary)})
val SecondaryContainerDark = Color(${toArgb(dark.secondaryContainer)})
val OnSecondaryContainerDark = Color(${toArgb(dark.onSecondaryContainer)})
val TertiaryDark = Color(${toArgb(dark.tertiary)})
val OnTertiaryDark = Color(${toArgb(dark.onTertiary)})
val TertiaryContainerDark = Color(${toArgb(dark.tertiaryContainer)})
val OnTertiaryContainerDark = Color(${toArgb(dark.onTertiaryContainer)})
val BackgroundDark = Color(${toArgb(dark.background)})
val OnBackgroundDark = Color(${toArgb(dark.onBackground)})
val SurfaceDark = Color(${toArgb(dark.surface)})
val OnSurfaceDark = Color(${toArgb(dark.onSurface)})
val SurfaceVariantDark = Color(${toArgb(dark.surfaceVariant)})
val OnSurfaceVariantDark = Color(${toArgb(dark.onSurfaceVariant)})
val OutlineDark = Color(${toArgb(dark.outline)})
val OutlineVariantDark = Color(${toArgb(dark.outlineVariant)})
`;
        }

        function generateThemeKt() {
            return `package com.example.compose.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext

private val LightColorScheme = lightColorScheme(
    primary = PrimaryLight,
    onPrimary = OnPrimaryLight,
    primaryContainer = PrimaryContainerLight,
    onPrimaryContainer = OnPrimaryContainerLight,
    secondary = SecondaryLight,
    onSecondary = OnSecondaryLight,
    secondaryContainer = SecondaryContainerLight,
    onSecondaryContainer = OnSecondaryContainerLight,
    tertiary = TertiaryLight,
    onTertiary = OnTertiaryLight,
    tertiaryContainer = TertiaryContainerLight,
    onTertiaryContainer = OnTertiaryContainerLight,
    background = BackgroundLight,
    onBackground = OnBackgroundLight,
    surface = SurfaceLight,
    onSurface = OnSurfaceLight,
    surfaceVariant = SurfaceVariantLight,
    onSurfaceVariant = OnSurfaceVariantLight,
    outline = OutlineLight,
    outlineVariant = OutlineVariantLight
)

private val DarkColorScheme = darkColorScheme(
    primary = PrimaryDark,
    onPrimary = OnPrimaryDark,
    primaryContainer = PrimaryContainerDark,
    onPrimaryContainer = OnPrimaryContainerDark,
    secondary = SecondaryDark,
    onSecondary = OnSecondaryDark,
    secondaryContainer = SecondaryContainerDark,
    onSecondaryContainer = OnSecondaryContainerDark,
    tertiary = TertiaryDark,
    onTertiary = OnTertiaryDark,
    tertiaryContainer = TertiaryContainerDark,
    onTertiaryContainer = OnTertiaryContainerDark,
    background = BackgroundDark,
    onBackground = OnBackgroundDark,
    surface = SurfaceDark,
    onSurface = OnSurfaceDark,
    surfaceVariant = SurfaceVariantDark,
    onSurfaceVariant = OnSurfaceVariantDark,
    outline = OutlineDark,
    outlineVariant = OutlineVariantDark
)

@Composable
fun AppTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    // Dynamic color is available on Android 12+
    dynamicColor: Boolean = false,
    content: @Composable () -> Unit
) {
    val colorScheme = when {
        dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
            val context = LocalContext.current
            if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        }
        darkTheme -> DarkColorScheme
        else -> LightColorScheme
    }

    MaterialTheme(
        colorScheme = colorScheme,
        content = content
    )
}
`;
        }

        function updateCodeDisplay() {
            const schemes = getCurrentSchemes();
            const codeEl = document.getElementById('tbCodeSnippet');
            if (!codeEl) return;

            const codeText = activeTab === 'theme' ? generateThemeKt() : generateColorKt(schemes.light, schemes.dark);
            codeEl.textContent = codeText;
            if (window.Prism) {
                Prism.highlightElement(codeEl);
            }
        }

        function switchCodeTab(tab) {
            activeTab = tab;
            document.getElementById('tabTheme').classList.toggle('active', tab === 'theme');
            document.getElementById('tabColor').classList.toggle('active', tab === 'color');
            document.getElementById('codeFileLabel').textContent = tab === 'theme' ? 'Theme.kt' : 'Color.kt';
            updateCodeDisplay();
        }

        function copyCurrentCode() {
            const codeEl = document.getElementById('tbCodeSnippet');
            if (!codeEl) return;
            navigator.clipboard.writeText(codeEl.innerText).then(() => {
                const btn = document.querySelector('#export-code .copy-btn');
                if (btn) {
                    const old = btn.textContent;
                    btn.textContent = 'Copied!';
                    setTimeout(() => { btn.textContent = old; }, 2000);
                }
            });
        }

        function syncWasm() {
            const frame = document.getElementById('wasmFrame');
            const hash = `snippet=theme-builder&theme=${currentMode}&preset=${currentPreset}&seed=${encodeURIComponent(currentSeed)}`;
            const fsBtn = document.getElementById('wasmFullscreenBtn');
            if (fsBtn) {
                const href = fsBtn.getAttribute('href') || '';
                const base = href.split('#')[0];
                fsBtn.setAttribute('href', `${base}#${hash}`);
            }
            if (frame && frame.contentWindow) {
                try {
                    frame.contentWindow.postMessage(JSON.stringify({
                        type: 'SET_THEME',
                        snippet: 'theme-builder',
                        theme: currentMode,
                        preset: currentPreset,
                        color: currentSeed
                    }), '*');
                } catch (e) {}
            }
        }

        function selectPreset(presetKey, btn) {
            currentPreset = presetKey;
            const p = PRESETS[presetKey];
            if (p) {
                currentSeed = p.seed;
                const picker = document.getElementById('tbSeedPicker');
                const hexIn = document.getElementById('tbSeedHex');
                if (picker) picker.value = currentSeed;
                if (hexIn) hexIn.value = currentSeed;
            }
            document.querySelectorAll('.tb-preset-btn').forEach(b => b.classList.remove('active'));
            if (btn) btn.classList.add('active');
            renderRoleSwatches();
            updateCodeDisplay();
            syncWasm();
        }

        function onCustomSeedChange(val) {
            currentPreset = 'custom';
            currentSeed = val.toUpperCase();
            const hexIn = document.getElementById('tbSeedHex');
            if (hexIn) hexIn.value = currentSeed;
            document.querySelectorAll('.tb-preset-btn').forEach(b => b.classList.remove('active'));
            renderRoleSwatches();
            updateCodeDisplay();
            syncWasm();
        }

        function onHexInputChange(val) {
            let clean = val.trim();
            if (!clean.startsWith('#')) clean = '#' + clean;
            if (/^#[0-9A-Fa-f]{6}$/.test(clean)) {
                currentPreset = 'custom';
                currentSeed = clean.toUpperCase();
                const picker = document.getElementById('tbSeedPicker');
                if (picker) picker.value = currentSeed;
                document.querySelectorAll('.tb-preset-btn').forEach(b => b.classList.remove('active'));
                renderRoleSwatches();
                updateCodeDisplay();
                syncWasm();
            }
        }

        function setAppMode(mode) {
            currentMode = mode;
            document.getElementById('btnModeLight').classList.toggle('active', mode === 'light');
            document.getElementById('btnModeDark').classList.toggle('active', mode === 'dark');
            renderRoleSwatches();
            updateCodeDisplay();
            syncWasm();
        }

        function toggleTheme() {
            const html = document.documentElement;
            const current = html.getAttribute('data-theme') || 'light';
            const next = current === 'light' ? 'dark' : 'light';
            html.setAttribute('data-theme', next);
            localStorage.setItem('theme', next);
            setAppMode(next);
        }

        function reloadWasm() {
            const frame = document.getElementById('wasmFrame');
            if (frame) frame.src = frame.src;
        }

        function toggleNavSub(target, event) {
            if (event) {
                event.preventDefault();
                event.stopPropagation();
            }
            const parentItem = target.closest('.nav-item-parent');
            if (!parentItem) return;
            const subList = parentItem.querySelector('.nav-sub-list');
            const arrow = parentItem.querySelector('.nav-sub-arrow');
            if (!subList) return;
            if (subList.style.display === 'none') {
                subList.style.display = 'block';
                if (arrow) arrow.innerHTML = '&#9662;';
            } else {
                subList.style.display = 'none';
                if (arrow) arrow.innerHTML = '&#9656;';
            }
        }

        function filterNav(query) {
            query = query.toLowerCase().trim();
            const categories = document.querySelectorAll('.nav-tree-category');
            categories.forEach(cat => {
                const items = cat.querySelectorAll('.nav-item');
                let catHasMatch = false;

                items.forEach(item => {
                    const title = item.getAttribute('data-title') || '';
                    const subList = item.querySelector('.nav-sub-list');
                    const subArrow = item.querySelector('.nav-sub-arrow');
                    const subItems = item.querySelectorAll('.nav-sub-item');
                    let itemMatch = title.includes(query);
                    let subMatch = false;

                    subItems.forEach(sub => {
                        const subTitle = sub.getAttribute('data-title') || '';
                        const match = subTitle.includes(query);
                        if (match) {
                            subMatch = true;
                            sub.style.display = 'block';
                        } else if (query) {
                            sub.style.display = 'none';
                        } else {
                            sub.style.display = 'block';
                        }
                    });

                    if (!query) {
                        item.style.display = 'block';
                        if (subList) {
                            subList.style.display = 'none';
                            if (subArrow) subArrow.innerHTML = '&#9656;';
                        }
                    } else if (itemMatch || subMatch) {
                        item.style.display = 'block';
                        catHasMatch = true;
                        if (subList) {
                            subList.style.display = 'block';
                            if (subArrow) subArrow.innerHTML = '&#9662;';
                        }
                    } else {
                        item.style.display = 'none';
                    }
                });

                cat.style.display = (!query || catHasMatch) ? 'block' : 'none';
            });
        }

        window.addEventListener('DOMContentLoaded', () => {
            const savedTheme = localStorage.getItem('theme') || 'light';
            document.documentElement.setAttribute('data-theme', savedTheme);
            setAppMode(savedTheme);

            const frame = document.getElementById('wasmFrame');
            if (frame) {
                frame.addEventListener('load', () => {
                    setTimeout(syncWasm, 200);
                });
            }

            const observer = new IntersectionObserver((entries) => {
                entries.forEach(entry => {
                    if (entry.isIntersecting) {
                        const id = entry.target.getAttribute('id');
                        document.querySelectorAll('.page-nav-link').forEach(link => {
                            link.classList.toggle('active', link.getAttribute('href') === '#' + id);
                        });
                    }
                });
            }, { rootMargin: '0px 0px -70% 0px' });

            document.querySelectorAll('article section, .page-header').forEach(section => {
                observer.observe(section);
            });
        });
    </script>
</body>
</html>
"""
    replacements = {
        "{{AUTOGENERATED_HEADER}}": autogenerated_header,
        "{{CSS_PATH}}": css_path,
        "{{BRAND_HREF}}": brand_href,
        "{{THEME_BUILDER_HEADER_HREF}}": theme_builder_header_href,
        "{{LEFT_SIDEBAR_HTML}}": left_sidebar_html,
        "{{WASM_SRC}}": wasm_src,
        "{{FULLSCREEN_HREF}}": fullscreen_href,
        "{{SCREENSHOT_SRC}}": screenshot_src,
        "{{PRISM_JS}}": prism_js,
        "{{PRISM_KT_JS}}": prism_kt_js,
        "{{INDEX_HREF}}": index_href,
        "{{PREV_HREF}}": prev_href,
        "{{REPORT_ISSUE_URL}}": report_issue_url,
    }

    result = template
    for k, v in replacements.items():
        result = result.replace(k, v)

    return result


