name: Deploy Compose Previews to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'compose/**'
      - 'preview/**'
      - '.github/workflows/deploy-preview-pages.yml'
  pull_request:
    paths:
      - 'compose/**'
      - 'preview/**'
      - '.github/workflows/deploy-preview-pages.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'pages-${{ github.ref }}'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - name: Set up Java 25
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6

      - name: Generate Preview Screenshots
        run: |
          ./gradlew :preview:generator:recordRoborazziDebug --stacktrace

      - name: Build WASM & Assemble Static Website
        run: |
          ./gradlew :preview:wasm:packageStaticSite --stacktrace

      - name: Setup Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Upload GitHub Pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: preview/wasm/build/dist/site

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
