name: Sync main and latest
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Merge main into latest
        run: git checkout latest && git merge main

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: 🤖 Sync main to latest
          committer: compose-devrel-github-bot <compose-devrel-github-bot@google.com>
          author: compose-devrel-github-bot <compose-devrel-github-bot@google.com>
          signoff: false
          branch: bot-sync-main
          delete-branch: true
          title: '🤖 Sync main to latest'
          body: Updated dependencies
          reviewers: ${{ github.actor }}
