name: Sync main and latest
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set git config user
        run: git config user.email "compose-devrel-github-bot@google.com" && git config user.name "compose-devrel-github-bot"

      - name: Merge main into latest
        run: git fetch && git switch latest && git merge -s ours origin/main --allow-unrelated-histories

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: 🤖 Sync main to latest
          committer: compose-devrel-github-bot <compose-devrel-github-bot@google.com>
          author: compose-devrel-github-bot <compose-devrel-github-bot@google.com>
          signoff: false
          branch: bot-sync-main
          delete-branch: true
          title: '🤖 Sync main to latest'
          body: 'Update `latest` with `main`'
          reviewers: ${{ github.actor }}
