name: Update Versions / Dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Update dependencies
        run: ./gradlew versionCatalogUpdate
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: 🤖 Update Dependencies
          committer: compose-devrel-github-bot <compose-devrel-github-bot@google.com>
          author: compose-devrel-github-bot <compose-devrel-github-bot@google.com>
          signoff: false
          branch: bot-update-deps
          delete-branch: true
          title: '🤖 Update Dependencies'
          body: Updated dependencies
          reviewers: ${{ github.actor }}
